spring.application.name=orchid-service
server.port=8082

spring.datasource.url=${ORCHID_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=OrchidServiceDb;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${ORCHID_DB_USERNAME:sa}
spring.datasource.password=${ORCHID_DB_PASSWORD:YourStrong!Passw0rd}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
